### ISSUE TITLE
Lesson plans:  basic hooks

### ISSUE THREAD

**Issue by mdewey** [suncoast-devs/handbook#34]
using [this template](https://github.com/suncoast-devs/handbook/blob/master/meta/lecture-template.md), create a lesson about react hooks. 

This should include: 
- useEffect
- useState

**Comment by rynatk** [comment]
grabbing this one!

**Comment by rynatk** [comment]
PR opened: https://github.com/suncoast-devs/handbook/pull/54

**Comment by gstark** [comment]
Merge this into the current structure on a lesson on hooks
