### ISSUE TITLE
Clean up homework assignents

### ISSUE THREAD

**Issue by mdewey** [suncoast-devs/handbook#48]
Expand the current Homework assignments
Including, but not limited to:
- Cleaning and betterment of exists assignments
- Create Wireframes, HTML, and CSS to give to students
- flushing out requirements
- Create answer keys
- Creation of new alternate homework assignments

**Comment by biggspidey** [comment]
Cleaning some of these up, will edit with which ones soon...

**Comment by alsleaders** [comment]
@biggspidey After you post what you're taking I'll see if I can pick up some of the other ones.

**Comment by gstark** [comment]
This will be better as individual issues for specific requests on specific assignments
